---
- hosts: all
  tasks:
    - name: Ensure keepalived is installed.
      package:
        name: keepalived
        state: present
    - name: Ensure nginx is installed.
      package:
        name: nginx
        state: present

    - name: Template keepalived config file
      template:
        src: keepalived.conf
        dest: /etc/keepalived/keepalived.conf
      notify:
        - Restart keepalived

    - name: Template keepalived_failover.sh
      template:
        src: keepalived_failover.sh
        dest: /etc/keepalived/
        mode: '744'

  handlers:
    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted
